#pragma once
#include "Disassembler.hpp"

namespace scrDbgApp
{
    class DisassemblerRDR2 : public Disassembler
    {
    public:
        using Disassembler::Disassembler;

        int GetInstructionSize(uint32_t pc) const override;
        bool IsJumpOrCall(uint8_t op) const override;
        uint32_t GetJumpTarget(uint32_t pc) const override;
        bool IsWildcard(uint8_t op) const override;
        bool IsXrefToPc(uint32_t pc, uint32_t targetPc) const override;
        std::string MakePattern(uint32_t start, int len) const override;
        bool IsPatternUnique(uint32_t start, int len) const override;
        BinarySearchPattern MakeStringSearchPatterns(const std::string& value) const override;
        const char* GetInstructionDescription(uint8_t op) const override;

    protected:
        void BuildFunction(uint32_t pc) override;
        std::string DecodeInstructionInternal(int index) const override;

    private:
        std::string GetFunctionName(uint32_t pc, uint32_t size) const;

        static inline constexpr std::array<InstructionTable, 179> m_InstructionTable = {{{"NOP", "No operation", ""},
            {"IADD", "Integer add", ""},
            {"ISUB", "Integer subtract", ""},
            {"IMUL", "Integer multiply", ""},
            {"IDIV", "Integer divide", ""},
            {"IMOD", "Integer modulo", ""},
            {"INOT", "Integer logical NOT", ""},
            {"INEG", "Integer negate", ""},
            {"IEQ", "Integer equal", ""},
            {"INE", "Integer not equal", ""},
            {"IGT", "Integer greater than", ""},
            {"IGE", "Integer greater or equal", ""},
            {"ILT", "Integer less than", ""},
            {"ILE", "Integer less or equal", ""},
            {"FADD", "Float add", ""},
            {"FSUB", "Float subtract", ""},
            {"FMUL", "Float multiply", ""},
            {"FDIV", "Float divide", ""},
            {"FMOD", "Float modulo", ""},
            {"FNEG", "Float negate", ""},
            {"FEQ", "Float equal", ""},
            {"FNE", "Float not equal", ""},
            {"FGT", "Float greater than", ""},
            {"FGE", "Float greater or equal", ""},
            {"FLT", "Float less than", ""},
            {"FLE", "Float less or equal", ""},
            {"VADD", "Vector3 add", ""},
            {"VSUB", "Vector3 subtract", ""},
            {"VMUL", "Vector3 multiply", ""},
            {"VDIV", "Vector3 divide", ""},
            {"VNEG", "Vector3 negate", ""},
            {"IAND", "Integer bitwise AND", ""},
            {"IOR", "Integer bitwise OR", ""},
            {"IXOR", "Integer bitwise XOR", ""},
            {"I2F", "Integer to float", ""},
            {"F2I", "Float to integer", ""},
            {"F2V", "Float to vector3", ""},
            {"PUSH_CONST_U8", "Push unsigned 8-bit constant", "a"},
            {"PUSH_CONST_U8_U8", "Push two unsigned 8-bit constants", "aa"},
            {"PUSH_CONST_U8_U8_U8", "Push three unsigned 8-bit constants", "aaa"},
            {"PUSH_CONST_U32", "Push unsigned 32-bit constant", "e"},
            {"PUSH_CONST_F", "Push float constant", "f"},
            {"DUP", "Duplicate top of stack", ""},
            {"DROP", "Drop top of stack", ""},
            {"NATIVE", "Call native command", "h"},
            {"ENTER", "Enter function frame", "n"},
            {"LEAVE", "Leave function frame", "aa"},
            {"LOAD", "Load value from reference", ""},
            {"STORE", "Store value to reference", ""},
            {"STORE_REV", "Store value to reference (reversed)", ""},
            {"LOAD_N", "Load array elements", ""},
            {"STORE_N", "Store array elements", ""},
            {"ARRAY_U8", "Push reference to array element using 8-bit element size", "a"},
            {"ARRAY_U8_LOAD", "Load array element using 8-bit element size", "a"},
            {"ARRAY_U8_STORE", "Store array element using 8-bit element size", "a"},
            {"LOCAL_U8", "Push reference to 8-bit local variable", "a"},
            {"LOCAL_U8_LOAD", "Load 8-bit local variable", "a"},
            {"LOCAL_U8_STORE", "Store 8-bit local variable", "a"},
            {"STATIC_U8", "Push reference to 8-bit static variable", "a"},
            {"STATIC_U8_LOAD", "Load 8-bit static variable", "a"},
            {"STATIC_U8_STORE", "Store 8-bit static variable", "a"},
            {"IADD_U8", "Integer add unsigned 8-bit constant", "a"},
            {"IOFFSET_U8_LOAD", "Load value at unsigned 8-bit offset", "a"},
            {"IOFFSET_U8_STORE", "Store value at unsigned 8-bit offset", "a"},
            {"IMUL_U8", "Integer multiply unsigned 8-bit constant", "a"},
            {"PUSH_CONST_S16", "Push signed 16-bit constant", "c"},
            {"IADD_S16", "Integer add signed 16-bit constant", "c"},
            {"IOFFSET_S16_LOAD", "Load value at signed 16-bit offset", "c"},
            {"IOFFSET_S16_STORE", "Store value at signed 16-bit offset", "c"},
            {"IMUL_S16", "Integer multiply signed 16-bit constant", "c"},
            {"ARRAY_U16", "Push reference to array element using 16-bit element size", "b"},
            {"ARRAY_U16_LOAD", "Load array element using 16-bit element size", "b"},
            {"ARRAY_U16_STORE", "Store array element using 16-bit element size", "b"},
            {"LOCAL_U16", "Push reference to 16-bit local variable", "b"},
            {"LOCAL_U16_LOAD", "Load 16-bit local variable", "b"},
            {"LOCAL_U16_STORE", "Store 16-bit local variable", "b"},
            {"STATIC_U16", "Push reference to 16-bit static variable", "b"},
            {"STATIC_U16_LOAD", "Load 16-bit static variable", "b"},
            {"STATIC_U16_STORE", "Store 16-bit static variable", "b"},
            {"GLOBAL_U16", "Push reference to 16-bit global variable", "b"},
            {"GLOBAL_U16_LOAD", "Load 16-bit global variable", "b"},
            {"GLOBAL_U16_STORE", "Store 16-bit global variable", "b"},
            {"CALL", "Call script function", "b"},
            {"CALL_U8H_1", "Call script function (address high byte 0x1)", "b"},
            {"CALL_U8H_2", "Call script function (address high byte 0x2)", "b"},
            {"CALL_U8H_3", "Call script function (address high byte 0x3)", "b"},
            {"CALL_U8H_4", "Call script function (address high byte 0x4)", "b"},
            {"CALL_U8H_5", "Call script function (address high byte 0x5)", "b"},
            {"CALL_U8H_6", "Call script function (address high byte 0x6)", "b"},
            {"CALL_U8H_7", "Call script function (address high byte 0x7)", "b"},
            {"CALL_U8H_8", "Call script function (address high byte 0x8)", "b"},
            {"CALL_U8H_9", "Call script function (address high byte 0x9)", "b"},
            {"CALL_U8H_A", "Call script function (address high byte 0xA)", "b"},
            {"CALL_U8H_B", "Call script function (address high byte 0xB)", "b"},
            {"CALL_U8H_C", "Call script function (address high byte 0xC)", "b"},
            {"CALL_U8H_D", "Call script function (address high byte 0xD)", "b"},
            {"CALL_U8H_E", "Call script function (address high byte 0xE)", "b"},
            {"CALL_U8H_F", "Call script function (address high byte 0xF)", "b"},
            {"J", "Unconditional jump", "g"},
            {"JZ", "Jump if zero", "g"},
            {"INE_J", "Integer not equal, jump", "g"},
            {"IEQ_J", "Integer equal, jump", "g"},
            {"ILE_J", "Integer less or equal, jump", "g"},
            {"ILT_J", "Integer less than, jump", "g"},
            {"IGE_J", "Integer greater or equal, jump", "g"},
            {"IGT_J", "Integer greater than, jump", "g"},
            {"GLOBAL_U24", "Push reference to 24-bit global variable", "d"},
            {"GLOBAL_U24_LOAD", "Load 24-bit global variable", "d"},
            {"GLOBAL_U24_STORE", "Store 24-bit global variable", "d"},
            {"PUSH_CONST_U24", "Push unsigned 24-bit constant", "d"},
            {"SWITCH", "Switch on integer value", "i"},
            {"STRING", "Push inline string pointer", "m"},
            {"ARRAY", "Push reference to inline array", "e"},
            {"NULL", "Push null reference", ""},
            {"TEXT_LABEL_ASSIGN_STRING", "Assign string to text label", "a"},
            {"TEXT_LABEL_ASSIGN_INT", "Assign int to text label", "a"},
            {"TEXT_LABEL_APPEND_STRING", "Append string to text label", "a"},
            {"TEXT_LABEL_APPEND_INT", "Append int to text label", "a"},
            {"TEXT_LABEL_COPY", "Copy text label", ""},
            {"CATCH", "Set up catch handler", ""},
            {"THROW", "Throw exception", ""},
            {"CALLINDIRECT", "Call script function via pointer", ""},
            {"LEAVE_0_0", "Leave function frame (0 args, 0 returns)", ""},
            {"LEAVE_0_1", "Leave function frame (0 args, 1 return)", ""},
            {"LEAVE_0_2", "Leave function frame (0 args, 2 returns)", ""},
            {"LEAVE_0_3", "Leave function frame (0 args, 3 returns)", ""},
            {"LEAVE_1_0", "Leave function frame (1 arg, 0 returns)", ""},
            {"LEAVE_1_1", "Leave function frame (1 arg, 1 return)", ""},
            {"LEAVE_1_2", "Leave function frame (1 arg, 2 returns)", ""},
            {"LEAVE_1_3", "Leave function frame (1 arg, 3 returns)", ""},
            {"LEAVE_2_0", "Leave function frame (2 args, 0 returns)", ""},
            {"LEAVE_2_1", "Leave function frame (2 args, 1 return)", ""},
            {"LEAVE_2_2", "Leave function frame (2 args, 2 returns)", ""},
            {"LEAVE_2_3", "Leave function frame (2 args, 3 returns)", ""},
            {"LEAVE_3_0", "Leave function frame (3 args, 0 returns)", ""},
            {"LEAVE_3_1", "Leave function frame (3 args, 1 return)", ""},
            {"LEAVE_3_2", "Leave function frame (3 args, 2 returns)", ""},
            {"LEAVE_3_3", "Leave function frame (3 args, 3 returns)", ""},
            {"PUSH_CONST_M1", "Push constant -1", ""},
            {"PUSH_CONST_0", "Push constant 0", ""},
            {"PUSH_CONST_1", "Push constant 1", ""},
            {"PUSH_CONST_2", "Push constant 2", ""},
            {"PUSH_CONST_3", "Push constant 3", ""},
            {"PUSH_CONST_4", "Push constant 4", ""},
            {"PUSH_CONST_5", "Push constant 5", ""},
            {"PUSH_CONST_6", "Push constant 6", ""},
            {"PUSH_CONST_7", "Push constant 7", ""},
            {"PUSH_CONST_FM1", "Push float constant -1.0", ""},
            {"PUSH_CONST_F0", "Push float constant 0.0", ""},
            {"PUSH_CONST_F1", "Push float constant 1.0", ""},
            {"PUSH_CONST_F2", "Push float constant 2.0", ""},
            {"PUSH_CONST_F3", "Push float constant 3.0", ""},
            {"PUSH_CONST_F4", "Push float constant 4.0", ""},
            {"PUSH_CONST_F5", "Push float constant 5.0", ""},
            {"PUSH_CONST_F6", "Push float constant 6.0", ""},
            {"PUSH_CONST_F7", "Push float constant 7.0", ""},
            {"PATCH_RET", "Return from patched function", ""},
            {"PATCH_TRAP_0", "Patch trap 0x0", ""},
            {"PATCH_TRAP_1", "Patch trap 0x1", ""},
            {"PATCH_TRAP_2", "Patch trap 0x2", ""},
            {"PATCH_TRAP_3", "Patch trap 0x3", ""},
            {"PATCH_TRAP_4", "Patch trap 0x4", ""},
            {"PATCH_TRAP_5", "Patch trap 0x5", ""},
            {"PATCH_TRAP_6", "Patch trap 0x6", ""},
            {"PATCH_TRAP_7", "Patch trap 0x7", ""},
            {"PATCH_TRAP_8", "Patch trap 0x8", ""},
            {"PATCH_TRAP_9", "Patch trap 0x9", ""},
            {"PATCH_TRAP_A", "Patch trap 0xA", ""},
            {"PATCH_TRAP_B", "Patch trap 0xB", ""},
            {"PATCH_TRAP_C", "Patch trap 0xC", ""},
            {"PATCH_TRAP_D", "Patch trap 0xD", ""},
            {"PATCH_TRAP_E", "Patch trap 0xE", ""},
            {"PATCH_TRAP_F", "Patch trap 0xF", ""},
            {"CALL_PATCH", "Call function in patch table", "d"},
            {"CALL_OUT_OF_PATCH", "Call function outside patch table", "d"},
            {"REF_LOAD", "Load value through reference", ""},
            {"REF_STORE", "Store value through reference", ""},
            {"VECTOR_STORE", "Store Vector3 components to reference", ""},
            {"VECTOR_MAKE", "Construct vector3 from stack values", ""}}};
    };
}