#pragma once
#include "Disassembler.hpp"

namespace scrDbgApp
{
    class DisassemblerGTA4 : public Disassembler
    {
    public:
        using Disassembler::Disassembler;

        std::optional<FunctionInfo> GetFunctionForPc(uint32_t pc) const override;
        int GetInstructionSize(uint32_t pc) const override;
        bool IsJumpOrCall(uint8_t op) const override;
        uint32_t GetJumpTarget(uint32_t pc) const override;
        bool IsWildcard(uint8_t op) const override;
        bool IsXrefToPc(uint32_t pc, uint32_t targetPc) const override;
        std::string MakePattern(uint32_t start, int len) const override;
        bool IsPatternUnique(uint32_t start, int len) const override;
        BinarySearchPattern MakeStringSearchPatterns(const std::string& value) const override;
        const char* GetInstructionDescription(uint8_t op) const override;

    protected:
        void BuildFunction(uint32_t pc) override;
        std::string DecodeInstructionInternal(int index) const override;

    private:
        std::unordered_map<uint32_t, uint32_t> m_PcToEntry;

        static inline constexpr std::array<InstructionTable, 256> m_InstructionTable = {{{"NOP", "No operation", ""},
            {"IADD", "Integer add", ""},
            {"ISUB", "Integer subtract", ""},
            {"IMUL", "Integer multiply", ""},
            {"IDIV", "Integer divide", ""},
            {"IMOD", "Integer modulo", ""},
            {"INOT", "Integer logical NOT", ""},
            {"INEG", "Integer negate", ""},
            {"IEQ", "Integer equal", ""},
            {"INE", "Integer not equal", ""},
            {"IGT", "Integer greater than", ""},
            {"IGE", "Integer greater or equal", ""},
            {"ILT", "Integer less than", ""},
            {"ILE", "Integer less or equal", ""},
            {"FADD", "Float add", ""},
            {"FSUB", "Float subtract", ""},
            {"FMUL", "Float multiply", ""},
            {"FDIV", "Float divide", ""},
            {"FMOD", "Float modulo", ""},
            {"FNEG", "Float negate", ""},
            {"FEQ", "Float equal", ""},
            {"FNE", "Float not equal", ""},
            {"FGT", "Float greater than", ""},
            {"FGE", "Float greater or equal", ""},
            {"FLT", "Float less than", ""},
            {"FLE", "Float less or equal", ""},
            {"VADD", "Vector3 add", ""},
            {"VSUB", "Vector3 subtract", ""},
            {"VMUL", "Vector3 multiply", ""},
            {"VDIV", "Vector3 divide", ""},
            {"VNEG", "Vector3 negate", ""},
            {"IAND", "Integer bitwise AND", ""},
            {"IOR", "Integer bitwise OR", ""},
            {"IXOR", "Integer bitwise XOR", ""},
            {"J", "Unconditional jump", "e"},
            {"JZ", "Jump if zero", "e"},
            {"JNZ", "Jump if not zero", "e"},
            {"I2F", "Integer to float", ""},
            {"F2I", "Float to integer", ""},
            {"F2V", "Float to vector3", ""},
            {"PUSH_CONST_S16", "Push signed 16-bit constant", "c"},
            {"PUSH_CONST_U32", "Push unsigned 32-bit constant", "e"},
            {"PUSH_CONST_F", "Push float constant", "f"},
            {"DUP", "Duplicate top of stack", ""},
            {"DROP", "Drop top of stack", ""},
            {"NATIVE", "Call native command", "h"},
            {"CALL", "Call script function", "e"},
            {"ENTER", "Enter function frame", "n"},
            {"LEAVE", "Leave function frame", "aa"},
            {"LOAD", "Load value from reference", ""},
            {"STORE", "Store value to reference", ""},
            {"STORE_REV", "Store value to reference (reversed)", ""},
            {"ARRAY_LOAD", "Load array elements", ""},
            {"ARRAY_STORE", "Store array elements", ""},
            {"LOCAL_0", "Push reference to local 0", ""},
            {"LOCAL_1", "Push reference to local 1", ""},
            {"LOCAL_2", "Push reference to local 2", ""},
            {"LOCAL_3", "Push reference to local 3", ""},
            {"LOCAL_4", "Push reference to local 4", ""},
            {"LOCAL_5", "Push reference to local 5", ""},
            {"LOCAL_6", "Push reference to local 6", ""},
            {"LOCAL_7", "Push reference to local 7", ""},
            {"LOCAL", "Push reference to local (indexed)", ""},
            {"STATIC", "Push reference to static (indexed)", ""},
            {"GLOBAL", "Push reference to global (indexed)", ""},
            {"ARRAY", "Index into array reference", ""},
            {"SWITCH", "Switch on integer value", "i"},
            {"STRING", "Push inline string pointer", "s"},
            {"NULL", "Push null reference", ""},
            {"TEXT_LABEL_ASSIGN_STRING", "Assign string to text label", "a"},
            {"TEXT_LABEL_ASSIGN_INT", "Assign int to text label", "a"},
            {"TEXT_LABEL_APPEND_STRING", "Append string to text label", "a"},
            {"TEXT_LABEL_APPEND_INT", "Append int to text label", "a"},
            {"CATCH", "Set up catch handler", ""},
            {"THROW", "Throw exception", ""},
            {"TEXT_LABEL_COPY", "Copy text label", ""},
            {"GETXPROTECT", "Get value from protected storage", ""},
            {"SETXPROTECT", "Set value in protected storage", ""},
            {"REFXPROTECT", "Reference protected storage", ""},
            {"EXIT", "Terminate script", ""},
            {"PUSH_CONST_M16", "Pushes constant -16", ""},
            {"PUSH_CONST_M15", "Pushes constant -15", ""},
            {"PUSH_CONST_M14", "Pushes constant -14", ""},
            {"PUSH_CONST_M13", "Pushes constant -13", ""},
            {"PUSH_CONST_M12", "Pushes constant -12", ""},
            {"PUSH_CONST_M11", "Pushes constant -11", ""},
            {"PUSH_CONST_M10", "Pushes constant -10", ""},
            {"PUSH_CONST_M9", "Pushes constant -9", ""},
            {"PUSH_CONST_M8", "Pushes constant -8", ""},
            {"PUSH_CONST_M7", "Pushes constant -7", ""},
            {"PUSH_CONST_M6", "Pushes constant -6", ""},
            {"PUSH_CONST_M5", "Pushes constant -5", ""},
            {"PUSH_CONST_M4", "Pushes constant -4", ""},
            {"PUSH_CONST_M3", "Pushes constant -3", ""},
            {"PUSH_CONST_M2", "Pushes constant -2", ""},
            {"PUSH_CONST_M1", "Pushes constant -1", ""},
            {"PUSH_CONST_0", "Pushes constant 0", ""},
            {"PUSH_CONST_1", "Pushes constant 1", ""},
            {"PUSH_CONST_2", "Pushes constant 2", ""},
            {"PUSH_CONST_3", "Pushes constant 3", ""},
            {"PUSH_CONST_4", "Pushes constant 4", ""},
            {"PUSH_CONST_5", "Pushes constant 5", ""},
            {"PUSH_CONST_6", "Pushes constant 6", ""},
            {"PUSH_CONST_7", "Pushes constant 7", ""},
            {"PUSH_CONST_8", "Pushes constant 8", ""},
            {"PUSH_CONST_9", "Pushes constant 9", ""},
            {"PUSH_CONST_10", "Pushes constant 10", ""},
            {"PUSH_CONST_11", "Pushes constant 11", ""},
            {"PUSH_CONST_12", "Pushes constant 12", ""},
            {"PUSH_CONST_13", "Pushes constant 13", ""},
            {"PUSH_CONST_14", "Pushes constant 14", ""},
            {"PUSH_CONST_15", "Pushes constant 15", ""},
            {"PUSH_CONST_16", "Pushes constant 16", ""},
            {"PUSH_CONST_17", "Pushes constant 17", ""},
            {"PUSH_CONST_18", "Pushes constant 18", ""},
            {"PUSH_CONST_19", "Pushes constant 19", ""},
            {"PUSH_CONST_20", "Pushes constant 20", ""},
            {"PUSH_CONST_21", "Pushes constant 21", ""},
            {"PUSH_CONST_22", "Pushes constant 22", ""},
            {"PUSH_CONST_23", "Pushes constant 23", ""},
            {"PUSH_CONST_24", "Pushes constant 24", ""},
            {"PUSH_CONST_25", "Pushes constant 25", ""},
            {"PUSH_CONST_26", "Pushes constant 26", ""},
            {"PUSH_CONST_27", "Pushes constant 27", ""},
            {"PUSH_CONST_28", "Pushes constant 28", ""},
            {"PUSH_CONST_29", "Pushes constant 29", ""},
            {"PUSH_CONST_30", "Pushes constant 30", ""},
            {"PUSH_CONST_31", "Pushes constant 31", ""},
            {"PUSH_CONST_32", "Pushes constant 32", ""},
            {"PUSH_CONST_33", "Pushes constant 33", ""},
            {"PUSH_CONST_34", "Pushes constant 34", ""},
            {"PUSH_CONST_35", "Pushes constant 35", ""},
            {"PUSH_CONST_36", "Pushes constant 36", ""},
            {"PUSH_CONST_37", "Pushes constant 37", ""},
            {"PUSH_CONST_38", "Pushes constant 38", ""},
            {"PUSH_CONST_39", "Pushes constant 39", ""},
            {"PUSH_CONST_40", "Pushes constant 40", ""},
            {"PUSH_CONST_41", "Pushes constant 41", ""},
            {"PUSH_CONST_42", "Pushes constant 42", ""},
            {"PUSH_CONST_43", "Pushes constant 43", ""},
            {"PUSH_CONST_44", "Pushes constant 44", ""},
            {"PUSH_CONST_45", "Pushes constant 45", ""},
            {"PUSH_CONST_46", "Pushes constant 46", ""},
            {"PUSH_CONST_47", "Pushes constant 47", ""},
            {"PUSH_CONST_48", "Pushes constant 48", ""},
            {"PUSH_CONST_49", "Pushes constant 49", ""},
            {"PUSH_CONST_50", "Pushes constant 50", ""},
            {"PUSH_CONST_51", "Pushes constant 51", ""},
            {"PUSH_CONST_52", "Pushes constant 52", ""},
            {"PUSH_CONST_53", "Pushes constant 53", ""},
            {"PUSH_CONST_54", "Pushes constant 54", ""},
            {"PUSH_CONST_55", "Pushes constant 55", ""},
            {"PUSH_CONST_56", "Pushes constant 56", ""},
            {"PUSH_CONST_57", "Pushes constant 57", ""},
            {"PUSH_CONST_58", "Pushes constant 58", ""},
            {"PUSH_CONST_59", "Pushes constant 59", ""},
            {"PUSH_CONST_60", "Pushes constant 60", ""},
            {"PUSH_CONST_61", "Pushes constant 61", ""},
            {"PUSH_CONST_62", "Pushes constant 62", ""},
            {"PUSH_CONST_63", "Pushes constant 63", ""},
            {"PUSH_CONST_64", "Pushes constant 64", ""},
            {"PUSH_CONST_65", "Pushes constant 65", ""},
            {"PUSH_CONST_66", "Pushes constant 66", ""},
            {"PUSH_CONST_67", "Pushes constant 67", ""},
            {"PUSH_CONST_68", "Pushes constant 68", ""},
            {"PUSH_CONST_69", "Pushes constant 69", ""},
            {"PUSH_CONST_70", "Pushes constant 70", ""},
            {"PUSH_CONST_71", "Pushes constant 71", ""},
            {"PUSH_CONST_72", "Pushes constant 72", ""},
            {"PUSH_CONST_73", "Pushes constant 73", ""},
            {"PUSH_CONST_74", "Pushes constant 74", ""},
            {"PUSH_CONST_75", "Pushes constant 75", ""},
            {"PUSH_CONST_76", "Pushes constant 76", ""},
            {"PUSH_CONST_77", "Pushes constant 77", ""},
            {"PUSH_CONST_78", "Pushes constant 78", ""},
            {"PUSH_CONST_79", "Pushes constant 79", ""},
            {"PUSH_CONST_80", "Pushes constant 80", ""},
            {"PUSH_CONST_81", "Pushes constant 81", ""},
            {"PUSH_CONST_82", "Pushes constant 82", ""},
            {"PUSH_CONST_83", "Pushes constant 83", ""},
            {"PUSH_CONST_84", "Pushes constant 84", ""},
            {"PUSH_CONST_85", "Pushes constant 85", ""},
            {"PUSH_CONST_86", "Pushes constant 86", ""},
            {"PUSH_CONST_87", "Pushes constant 87", ""},
            {"PUSH_CONST_88", "Pushes constant 88", ""},
            {"PUSH_CONST_89", "Pushes constant 89", ""},
            {"PUSH_CONST_90", "Pushes constant 90", ""},
            {"PUSH_CONST_91", "Pushes constant 91", ""},
            {"PUSH_CONST_92", "Pushes constant 92", ""},
            {"PUSH_CONST_93", "Pushes constant 93", ""},
            {"PUSH_CONST_94", "Pushes constant 94", ""},
            {"PUSH_CONST_95", "Pushes constant 95", ""},
            {"PUSH_CONST_96", "Pushes constant 96", ""},
            {"PUSH_CONST_97", "Pushes constant 97", ""},
            {"PUSH_CONST_98", "Pushes constant 98", ""},
            {"PUSH_CONST_99", "Pushes constant 99", ""},
            {"PUSH_CONST_100", "Pushes constant 100", ""},
            {"PUSH_CONST_101", "Pushes constant 101", ""},
            {"PUSH_CONST_102", "Pushes constant 102", ""},
            {"PUSH_CONST_103", "Pushes constant 103", ""},
            {"PUSH_CONST_104", "Pushes constant 104", ""},
            {"PUSH_CONST_105", "Pushes constant 105", ""},
            {"PUSH_CONST_106", "Pushes constant 106", ""},
            {"PUSH_CONST_107", "Pushes constant 107", ""},
            {"PUSH_CONST_108", "Pushes constant 108", ""},
            {"PUSH_CONST_109", "Pushes constant 109", ""},
            {"PUSH_CONST_110", "Pushes constant 110", ""},
            {"PUSH_CONST_111", "Pushes constant 111", ""},
            {"PUSH_CONST_112", "Pushes constant 112", ""},
            {"PUSH_CONST_113", "Pushes constant 113", ""},
            {"PUSH_CONST_114", "Pushes constant 114", ""},
            {"PUSH_CONST_115", "Pushes constant 115", ""},
            {"PUSH_CONST_116", "Pushes constant 116", ""},
            {"PUSH_CONST_117", "Pushes constant 117", ""},
            {"PUSH_CONST_118", "Pushes constant 118", ""},
            {"PUSH_CONST_119", "Pushes constant 119", ""},
            {"PUSH_CONST_120", "Pushes constant 120", ""},
            {"PUSH_CONST_121", "Pushes constant 121", ""},
            {"PUSH_CONST_122", "Pushes constant 122", ""},
            {"PUSH_CONST_123", "Pushes constant 123", ""},
            {"PUSH_CONST_124", "Pushes constant 124", ""},
            {"PUSH_CONST_125", "Pushes constant 125", ""},
            {"PUSH_CONST_126", "Pushes constant 126", ""},
            {"PUSH_CONST_127", "Pushes constant 127", ""},
            {"PUSH_CONST_128", "Pushes constant 128", ""},
            {"PUSH_CONST_129", "Pushes constant 129", ""},
            {"PUSH_CONST_130", "Pushes constant 130", ""},
            {"PUSH_CONST_131", "Pushes constant 131", ""},
            {"PUSH_CONST_132", "Pushes constant 132", ""},
            {"PUSH_CONST_133", "Pushes constant 133", ""},
            {"PUSH_CONST_134", "Pushes constant 134", ""},
            {"PUSH_CONST_135", "Pushes constant 135", ""},
            {"PUSH_CONST_136", "Pushes constant 136", ""},
            {"PUSH_CONST_137", "Pushes constant 137", ""},
            {"PUSH_CONST_138", "Pushes constant 138", ""},
            {"PUSH_CONST_139", "Pushes constant 139", ""},
            {"PUSH_CONST_140", "Pushes constant 140", ""},
            {"PUSH_CONST_141", "Pushes constant 141", ""},
            {"PUSH_CONST_142", "Pushes constant 142", ""},
            {"PUSH_CONST_143", "Pushes constant 143", ""},
            {"PUSH_CONST_144", "Pushes constant 144", ""},
            {"PUSH_CONST_145", "Pushes constant 145", ""},
            {"PUSH_CONST_146", "Pushes constant 146", ""},
            {"PUSH_CONST_147", "Pushes constant 147", ""},
            {"PUSH_CONST_148", "Pushes constant 148", ""},
            {"PUSH_CONST_149", "Pushes constant 149", ""},
            {"PUSH_CONST_150", "Pushes constant 150", ""},
            {"PUSH_CONST_151", "Pushes constant 151", ""},
            {"PUSH_CONST_152", "Pushes constant 152", ""},
            {"PUSH_CONST_153", "Pushes constant 153", ""},
            {"PUSH_CONST_154", "Pushes constant 154", ""},
            {"PUSH_CONST_155", "Pushes constant 155", ""},
            {"PUSH_CONST_156", "Pushes constant 156", ""},
            {"PUSH_CONST_157", "Pushes constant 157", ""},
            {"PUSH_CONST_158", "Pushes constant 158", ""},
            {"PUSH_CONST_159", "Pushes constant 159", ""}}};
    };
}