#pragma once
#include "Disassembler.hpp"

namespace scrDbgApp
{
    class DisassemblerRDR3 : public Disassembler
    {
    public:
        using Disassembler::Disassembler;

        int GetInstructionSize(uint32_t pc) const override;
        bool IsJumpOrCall(uint8_t op) const override;
        uint32_t GetJumpTarget(uint32_t pc) const override;
        bool IsWildcard(uint8_t op) const override;
        bool IsXrefToPc(uint32_t pc, uint32_t targetPc) const override;
        std::string MakePattern(uint32_t start, int len) const override;
        bool IsPatternUnique(uint32_t start, int len) const override;
        BinarySearchPattern MakeStringSearchPatterns(const std::string& value) const override;
        const char* GetInstructionDescription(uint8_t op) const override;

    protected:
        void BuildFunction(uint32_t pc) override;
        std::string DecodeInstructionInternal(int index) const override;

    private:
        std::string GetFunctionName(uint32_t pc, uint32_t size) const;
        std::optional<uint32_t> GetStringIndex(uint32_t pc) const;

        enum Opcodes : uint8_t
        {
            NOP = 19,
            IADD = 67,
            ISUB = 16,
            IMUL = 30,
            IDIV = 89,
            IMOD = 71,
            INOT = 5,
            INEG = 43,
            IEQ = 11,
            INE = 28,
            IGT = 32,
            IGE = 126,
            ILT = 53,
            ILE = 119,
            FADD = 113,
            FSUB = 81,
            FMUL = 36,
            FDIV = 12,
            FMOD = 27,
            FNEG = 101,
            FEQ = 125,
            FNE = 87,
            FGT = 49,
            FGE = 22,
            FLT = 52,
            FLE = 132,
            VADD = 96,
            VSUB = 25,
            VMUL = 7,
            VDIV = 18,
            VNEG = 97,
            IAND = 105,
            IOR = 48,
            IXOR = 73,
            I2F = 54,
            F2I = 69,
            F2V = 56,
            PUSH_CONST_U8 = 109,
            PUSH_CONST_U8_U8 = 111,
            PUSH_CONST_U8_U8_U8 = 123,
            PUSH_CONST_U32 = 55,
            PUSH_CONST_F = 134,
            DUP = 106,
            DROP = 65,
            NATIVE = 3,
            ENTER = 34,
            LEAVE = 80,
            LOAD = 118,
            STORE = 50,
            STORE_REV = 61,
            LOAD_N = 45,
            STORE_N = 6,
            ARRAY_U8 = 99,
            ARRAY_U8_LOAD = 23,
            ARRAY_U8_STORE = 100,
            LOCAL_U8 = 75,
            LOCAL_U8_LOAD = 102,
            LOCAL_U8_STORE = 103,
            STATIC_U8 = 137,
            STATIC_U8_LOAD = 84,
            STATIC_U8_STORE = 78,
            IADD_U8 = 92,
            IMUL_U8 = 20,
            IOFFSET = 86,
            IOFFSET_U8 = 128,
            IOFFSET_U8_LOAD = 39,
            IOFFSET_U8_STORE = 108,
            PUSH_CONST_S16 = 37,
            IADD_S16 = 59,
            IMUL_S16 = 127,
            IOFFSET_S16 = 24,
            IOFFSET_S16_LOAD = 120,
            IOFFSET_S16_STORE = 140,
            ARRAY_U16 = 64,
            ARRAY_U16_LOAD = 2,
            ARRAY_U16_STORE = 10,
            LOCAL_U16 = 88,
            LOCAL_U16_LOAD = 1,
            LOCAL_U16_STORE = 68,
            STATIC_U16 = 70,
            STATIC_U16_LOAD = 58,
            STATIC_U16_STORE = 95,
            GLOBAL_U16 = 135,
            GLOBAL_U16_LOAD = 112,
            GLOBAL_U16_STORE = 74,
            J = 104,
            JZ = 139,
            IEQ_JZ = 21,
            INE_JZ = 114,
            IGT_JZ = 46,
            IGE_JZ = 117,
            ILT_JZ = 138,
            ILE_JZ = 35,
            CALL = 57,
            GLOBAL_U24 = 93,
            GLOBAL_U24_LOAD = 133,
            GLOBAL_U24_STORE = 38,
            PUSH_CONST_U24 = 33,
            SWITCH = 60,
            STRING = 4,
            STRINGHASH = 129,
            TEXT_LABEL_ASSIGN_STRING = 31,
            TEXT_LABEL_ASSIGN_INT = 121,
            TEXT_LABEL_APPEND_STRING = 94,
            TEXT_LABEL_APPEND_INT = 41,
            TEXT_LABEL_COPY = 26,
            CATCH = 110,
            THROW = 85,
            CALLINDIRECT = 141,
            PUSH_CONST_M1 = 8,
            PUSH_CONST_0 = 47,
            PUSH_CONST_1 = 9,
            PUSH_CONST_2 = 17,
            PUSH_CONST_3 = 29,
            PUSH_CONST_4 = 66,
            PUSH_CONST_5 = 98,
            PUSH_CONST_6 = 77,
            PUSH_CONST_7 = 13,
            PUSH_CONST_FM1 = 76,
            PUSH_CONST_F0 = 115,
            PUSH_CONST_F1 = 72,
            PUSH_CONST_F2 = 91,
            PUSH_CONST_F3 = 44,
            PUSH_CONST_F4 = 90,
            PUSH_CONST_F5 = 124,
            PUSH_CONST_F6 = 122,
            PUSH_CONST_F7 = 51,
            LOCAL_LOAD_S = 15,
            LOCAL_STORE_S = 0,
            LOCAL_STORE_SR = 82,
            STATIC_LOAD_S = 14,
            STATIC_STORE_S = 79,
            STATIC_STORE_SR = 116,
            LOAD_N_S = 136,
            STORE_N_S = 83,
            STORE_N_SR = 130,
            GLOBAL_LOAD_S = 131,
            GLOBAL_STORE_S = 63,
            GLOBAL_STORE_SR = 42,
            STATIC_U24 = 62,
            STATIC_U24_LOAD = 107,
            STATIC_U24_STORE = 40
        };

        static inline constexpr std::array<InstructionTable, 142> m_InstructionTable = {{
            {"LOCAL_STORE_S", "Store secure local variable", ""},
            {"LOCAL_U16_LOAD", "Load 16-bit local variable", "b"},
            {"ARRAY_U16_LOAD", "Load array element using 16-bit element size", "b"},
            {"NATIVE", "Call native command", "h"},
            {"STRING", "Push reference to string using the index on the top of the stack", "m"},
            {"INOT", "Integer logical NOT", ""},
            {"STORE_N", "Store array elements", ""},
            {"VMUL", "Vector3 multiply", ""},
            {"PUSH_CONST_M1", "Push constant -1", ""},
            {"PUSH_CONST_1", "Push constant 1", ""},
            {"ARRAY_U16_STORE", "Store array element using 16-bit element size", "b"},
            {"IEQ", "Integer equal", ""},
            {"FDIV", "Float divide", ""},
            {"PUSH_CONST_7", "Push constant 7", ""},
            {"STATIC_LOAD_S", "Load secure static variable", ""},
            {"LOCAL_LOAD_S", "Load secure local variable", ""},
            {"ISUB", "Integer subtract", ""},
            {"PUSH_CONST_2", "Push constant 2", ""},
            {"VDIV", "Vector3 divide", ""},
            {"NOP", "No operation", ""},
            {"IMUL_U8", "Integer multiply unsigned 8-bit constant", "a"},
            {"IEQ_JZ", "Integer not equal, jump", "g"},
            {"FGE", "Float greater or equal", ""},
            {"ARRAY_U8_LOAD", "Load array element using 8-bit element size", "a"},
            {"IOFFSET_S16", "Push reference to struct field at offset S16 * 8", "c"},
            {"VSUB", "Vector3 subtract", ""},
            {"TEXT_LABEL_COPY", "Copy text label", ""},
            {"FMOD", "Float modulo", ""},
            {"INE", "Integer not equal", ""},
            {"PUSH_CONST_3", "Push constant 3", ""},
            {"IMUL", "Integer multiply", ""},
            {"TEXT_LABEL_ASSIGN_STRING", "Assign string to text label", "a"},
            {"IGT", "Integer greater than", ""},
            {"PUSH_CONST_U24", "Push unsigned 24-bit constant", "d"},
            {"ENTER", "Enter function frame", "n"},
            {"ILE_JZ", "Integer greater, jump", "g"},
            {"FMUL", "Float multiply", ""},
            {"PUSH_CONST_S16", "Push signed 16-bit constant", "c"},
            {"GLOBAL_U24_STORE", "Store 24-bit global variable", "d"},
            {"IOFFSET_U8_LOAD", "Load value at unsigned 8-bit offset", "a"},
            {"STATIC_U24_STORE", "Store 24-bit static variable", "d"},
            {"TEXT_LABEL_APPEND_INT", "Append int to text label", "a"},
            {"STORE_N_SR", "Store secure array elements 2", ""},
            {"INEG", "Integer negate", ""},
            {"PUSH_CONST_F3", "Push float constant 3.0", ""},
            {"LOAD_N", "Load array elements", ""},
            {"IGT_JZ", "Integer less or equal, jump", "g"},
            {"PUSH_CONST_0", "Push constant 0", ""},
            {"IOR", "Integer bitwise OR", ""},
            {"FGT", "Float greater than", ""},
            {"STORE", "Store value to reference", ""},
            {"PUSH_CONST_F7", "Push float constant 7.0", ""},
            {"FLT", "Float less than", ""},
            {"ILT", "Integer less than", ""},
            {"I2F", "Integer to float", ""},
            {"PUSH_CONST_U32", "Push unsigned 32-bit constant", "e"},
            {"F2V", "Float to vector3", ""},
            {"CALL", "Call script function", "d"},
            {"STATIC_U16_LOAD", "Load 16-bit static variable", "b"},
            {"IADD_S16", "Integer add signed 16-bit constant", "c"},
            {"SWITCH", "Switch on integer value", "i"},
            {"STORE_REV", "Store value to reference (reversed)", ""},
            {"STATIC_U24", "Push reference to 24-bit static variable", "d"},
            {"STORE_N_S", "Store secure array elements", ""},
            {"ARRAY_U16", "Push reference to array element using 16-bit element size", "b"},
            {"DROP", "Drop top of stack", ""},
            {"PUSH_CONST_4", "Push constant 4", ""},
            {"IADD", "Integer add", ""},
            {"LOCAL_U16_STORE", "Store 16-bit local variable", "b"},
            {"F2I", "Float to integer", ""},
            {"STATIC_U16", "Push reference to 16-bit static variable", "b"},
            {"IMOD", "Integer modulo", ""},
            {"PUSH_CONST_F1", "Push float constant 1.0", ""},
            {"IXOR", "Integer bitwise XOR", ""},
            {"GLOBAL_U16_STORE", "Store 16-bit global variable", "b"},
            {"LOCAL_U8", "Push reference to 8-bit local variable", "a"},
            {"PUSH_CONST_FM1", "Push float constant -1.0", ""},
            {"PUSH_CONST_6", "Push constant 6", ""},
            {"STATIC_U8_STORE", "Store 8-bit static variable", "a"},
            {"STATIC_STORE_S", "Store secure static variable", ""},
            {"LEAVE", "Leave function frame", "aa"},
            {"FSUB", "Float subtract", ""},
            {"LOCAL_STORE_SR", "Store secure local variable 2", ""},
            {"GLOBAL_STORE_S", "Store secure global variable", ""},
            {"STATIC_U8_LOAD", "Load 8-bit static variable", "a"},
            {"THROW", "Throw exception", ""},
            {"IOFFSET", "Push reference to struct field indexed by the popped index * 8", ""},
            {"FNE", "Float not equal", ""},
            {"LOCAL_U16", "Push reference to 16-bit local variable", "b"},
            {"IDIV", "Integer divide", ""},
            {"PUSH_CONST_F4", "Push float constant 4.0", ""},
            {"PUSH_CONST_F2", "Push float constant 2.0", ""},
            {"IADD_U8", "Integer add unsigned 8-bit constant", "a"},
            {"GLOBAL_U24", "Push reference to 24-bit global variable", "d"},
            {"TEXT_LABEL_APPEND_STRING", "Append string to text label", "a"},
            {"STATIC_U16_STORE", "Store 16-bit static variable", "b"},
            {"VADD", "Vector3 add", ""},
            {"VNEG", "Vector3 negate", ""},
            {"PUSH_CONST_5", "Push constant 5", ""},
            {"ARRAY_U8", "Push reference to array element using 8-bit element size", "a"},
            {"ARRAY_U8_STORE", "Store array element using 8-bit element size", "a"},
            {"FNEG", "Float negate", ""},
            {"LOCAL_U8_LOAD", "Load 8-bit local variable", "a"},
            {"LOCAL_U8_STORE", "Store 8-bit local variable", "a"},
            {"J", "Unconditional jump", "g"},
            {"IAND", "Integer bitwise AND", ""},
            {"DUP", "Duplicate top of stack", ""},
            {"STATIC_U24_LOAD", "Load 24-bit static variable", "d"},
            {"IOFFSET_U8_STORE", "Store value at unsigned 8-bit offset", "a"},
            {"PUSH_CONST_U8", "Push unsigned 8-bit constant", "a"},
            {"CATCH", "Set up catch handler", ""},
            {"PUSH_CONST_U8_U8", "Push two unsigned 8-bit constants", "aa"},
            {"GLOBAL_U16_LOAD", "Load 16-bit global variable", "b"},
            {"FADD", "Float add", ""},
            {"INE_JZ", "Integer equal, jump", "g"},
            {"PUSH_CONST_F0", "Push float constant 0.0", ""},
            {"STATIC_STORE_SR", "Store secure static variable 2", ""},
            {"IGE_JZ", "Integer less than, jump", "g"},
            {"LOAD", "Load value from reference", ""},
            {"ILE", "Integer less or equal", ""},
            {"IOFFSET_S16_LOAD", "Load value at signed 16-bit offset", "c"},
            {"TEXT_LABEL_ASSIGN_INT", "Assign int to text label", "a"},
            {"PUSH_CONST_F6", "Push float constant 6.0", ""},
            {"PUSH_CONST_U8_U8_U8", "Push three unsigned 8-bit constants", "aaa"},
            {"PUSH_CONST_F5", "Push float constant 5.0", ""},
            {"FEQ", "Float equal", ""},
            {"IGE", "Integer greater or equal", ""},
            {"IMUL_S16", "Integer multiply signed 16-bit constant", "c"},
            {"IOFFSET_U8", "Push reference to struct field at offset U8 * 8", "a"},
            {"STRINGHASH", "Hash the string with JOAAT", ""},
            {"GLOBAL_STORE_SR", "Store secure global variable 2", ""},
            {"GLOBAL_LOAD_S", "Load secure global variable", ""},
            {"FLE", "Float less or equal", ""},
            {"GLOBAL_U24_LOAD", "Load 24-bit global variable", "d"},
            {"PUSH_CONST_F", "Push float constant", "f"},
            {"GLOBAL_U16", "Push reference to 16-bit global variable", "b"},
            {"LOAD_N_S", "Load secure array elements", ""},
            {"STATIC_U8", "Push reference to 8-bit static variable", "a"},
            {"ILT_JZ", "Integer greater or equal, jump", "g"},
            {"JZ", "Jump if zero", "g"},
            {"IOFFSET_S16_STORE", "Store value at signed 16-bit offset", "c"},
            {"CALLINDIRECT", "Call script function via pointer", ""},
        }};
    };
}