#pragma once
#include "Disassembler.hpp"

namespace scrDbgApp
{
    class DisassemblerRDR3 : public Disassembler
    {
    public:
        using Disassembler::Disassembler;

        int GetInstructionSize(uint32_t pc) const override;
        bool IsJumpOrCall(uint8_t op) const override;
        uint32_t GetJumpTarget(uint32_t pc) const override;
        bool IsWildcard(uint8_t op) const override;
        bool IsXrefToPc(uint32_t pc, uint32_t targetPc) const override;
        std::string MakePattern(uint32_t start, int len) const override;
        bool IsPatternUnique(uint32_t start, int len) const override;
        BinarySearchPattern MakeStringSearchPatterns(const std::string& value) const override;
        const char* GetInstructionDescription(uint8_t op) const override;

    protected:
        void BuildFunction(uint32_t pc) override;
        std::string DecodeInstructionInternal(int index) const override;

    private:
        std::string GetFunctionName(uint32_t pc, uint32_t size) const;
        std::optional<uint32_t> GetStringIndex(uint32_t pc) const;

        static inline constexpr std::array<InstructionTable, 142> m_InstructionTable = {{
            {"LOCAL_STORE_S", "Store secure local variable", ""},
            {"LOCAL_U16_LOAD", "Load 16-bit local variable", "b"},
            {"ARRAY_U16_LOAD", "Load array element using 16-bit element size", "b"},
            {"NATIVE", "Call native command", "h"},
            {"STRING", "Push reference to string using the index on the top of the stack", "m"},
            {"INOT", "Integer logical NOT", ""},
            {"STORE_N", "Store array elements", ""},
            {"VMUL", "Vector3 multiply", ""},
            {"PUSH_CONST_M1", "Push constant -1", ""},
            {"PUSH_CONST_1", "Push constant 1", ""},
            {"ARRAY_U16_STORE", "Store array element using 16-bit element size", "b"},
            {"IEQ", "Integer equal", ""},
            {"FDIV", "Float divide", ""},
            {"PUSH_CONST_7", "Push constant 7", ""},
            {"STATIC_LOAD_S", "Load secure static variable", ""},
            {"LOCAL_LOAD_S", "Load secure local variable", ""},
            {"ISUB", "Integer subtract", ""},
            {"PUSH_CONST_2", "Push constant 2", ""},
            {"VDIV", "Vector3 divide", ""},
            {"NOP", "No operation", ""},
            {"IMUL_U8", "Integer multiply unsigned 8-bit constant", "a"},
            {"IEQ_JZ", "Integer not equal, jump", "g"},
            {"FGE", "Float greater or equal", ""},
            {"ARRAY_U8_LOAD", "Load array element using 8-bit element size", "a"},
            {"IOFFSET_S16", "Push reference to struct field at offset S16 * 8", "c"},
            {"VSUB", "Vector3 subtract", ""},
            {"TEXT_LABEL_COPY", "Copy text label", ""},
            {"FMOD", "Float modulo", ""},
            {"INE", "Integer not equal", ""},
            {"PUSH_CONST_3", "Push constant 3", ""},
            {"IMUL", "Integer multiply", ""},
            {"TEXT_LABEL_ASSIGN_STRING", "Assign string to text label", "a"},
            {"IGT", "Integer greater than", ""},
            {"PUSH_CONST_U24", "Push unsigned 24-bit constant", "d"},
            {"ENTER", "Enter function frame", "n"},
            {"ILE_JZ", "Integer greater, jump", "g"},
            {"FMUL", "Float multiply", ""},
            {"PUSH_CONST_S16", "Push signed 16-bit constant", "c"},
            {"GLOBAL_U24_STORE", "Store 24-bit global variable", "d"},
            {"IOFFSET_U8_LOAD", "Load value at unsigned 8-bit offset", "a"},
            {"STATIC_U24_STORE", "Store 24-bit static variable", "d"},
            {"TEXT_LABEL_APPEND_INT", "Append int to text label", "a"},
            {"STORE_N_SR", "Store secure array elements 2", ""},
            {"INEG", "Integer negate", ""},
            {"PUSH_CONST_F3", "Push float constant 3.0", ""},
            {"LOAD_N", "Load array elements", ""},
            {"IGT_JZ", "Integer less or equal, jump", "g"},
            {"PUSH_CONST_0", "Push constant 0", ""},
            {"IOR", "Integer bitwise OR", ""},
            {"FGT", "Float greater than", ""},
            {"STORE", "Store value to reference", ""},
            {"PUSH_CONST_F7", "Push float constant 7.0", ""},
            {"FLT", "Float less than", ""},
            {"ILT", "Integer less than", ""},
            {"I2F", "Integer to float", ""},
            {"PUSH_CONST_U32", "Push unsigned 32-bit constant", "e"},
            {"F2V", "Float to vector3", ""},
            {"CALL", "Call script function", "d"},
            {"STATIC_U16_LOAD", "Load 16-bit static variable", "b"},
            {"IADD_S16", "Integer add signed 16-bit constant", "c"},
            {"SWITCH", "Switch on integer value", "i"},
            {"STORE_REV", "Store value to reference (reversed)", ""},
            {"STATIC_U24", "Push reference to 24-bit static variable", "d"},
            {"STORE_N_S", "Store secure array elements", ""},
            {"ARRAY_U16", "Push reference to array element using 16-bit element size", "b"},
            {"DROP", "Drop top of stack", ""},
            {"PUSH_CONST_4", "Push constant 4", ""},
            {"IADD", "Integer add", ""},
            {"LOCAL_U16_STORE", "Store 16-bit local variable", "b"},
            {"F2I", "Float to integer", ""},
            {"STATIC_U16", "Push reference to 16-bit static variable", "b"},
            {"IMOD", "Integer modulo", ""},
            {"PUSH_CONST_F1", "Push float constant 1.0", ""},
            {"IXOR", "Integer bitwise XOR", ""},
            {"GLOBAL_U16_STORE", "Store 16-bit global variable", "b"},
            {"LOCAL_U8", "Push reference to 8-bit local variable", "a"},
            {"PUSH_CONST_FM1", "Push float constant -1.0", ""},
            {"PUSH_CONST_6", "Push constant 6", ""},
            {"STATIC_U8_STORE", "Store 8-bit static variable", "a"},
            {"STATIC_STORE_S", "Store secure static variable", ""},
            {"LEAVE", "Leave function frame", "aa"},
            {"FSUB", "Float subtract", ""},
            {"LOCAL_STORE_SR", "Store secure local variable 2", ""},
            {"GLOBAL_STORE_S", "Store secure global variable", ""},
            {"STATIC_U8_LOAD", "Load 8-bit static variable", "a"},
            {"THROW", "Throw exception", ""},
            {"IOFFSET", "Push reference to struct field indexed by the popped index * 8", ""},
            {"FNE", "Float not equal", ""},
            {"LOCAL_U16", "Push reference to 16-bit local variable", "b"},
            {"IDIV", "Integer divide", ""},
            {"PUSH_CONST_F4", "Push float constant 4.0", ""},
            {"PUSH_CONST_F2", "Push float constant 2.0", ""},
            {"IADD_U8", "Integer add unsigned 8-bit constant", "a"},
            {"GLOBAL_U24", "Push reference to 24-bit global variable", "d"},
            {"TEXT_LABEL_APPEND_STRING", "Append string to text label", "a"},
            {"STATIC_U16_STORE", "Store 16-bit static variable", "b"},
            {"VADD", "Vector3 add", ""},
            {"VNEG", "Vector3 negate", ""},
            {"PUSH_CONST_5", "Push constant 5", ""},
            {"ARRAY_U8", "Push reference to array element using 8-bit element size", "a"},
            {"ARRAY_U8_STORE", "Store array element using 8-bit element size", "a"},
            {"FNEG", "Float negate", ""},
            {"LOCAL_U8_LOAD", "Load 8-bit local variable", "a"},
            {"LOCAL_U8_STORE", "Store 8-bit local variable", "a"},
            {"J", "Unconditional jump", "g"},
            {"IAND", "Integer bitwise AND", ""},
            {"DUP", "Duplicate top of stack", ""},
            {"STATIC_U24_LOAD", "Load 24-bit static variable", "d"},
            {"IOFFSET_U8_STORE", "Store value at unsigned 8-bit offset", "a"},
            {"PUSH_CONST_U8", "Push unsigned 8-bit constant", "a"},
            {"CATCH", "Set up catch handler", ""},
            {"PUSH_CONST_U8_U8", "Push two unsigned 8-bit constants", "aa"},
            {"GLOBAL_U16_LOAD", "Load 16-bit global variable", "b"},
            {"FADD", "Float add", ""},
            {"INE_JZ", "Integer equal, jump", "g"},
            {"PUSH_CONST_F0", "Push float constant 0.0", ""},
            {"STATIC_STORE_SR", "Store secure static variable 2", ""},
            {"IGE_JZ", "Integer less than, jump", "g"},
            {"LOAD", "Load value from reference", ""},
            {"ILE", "Integer less or equal", ""},
            {"IOFFSET_S16_LOAD", "Load value at signed 16-bit offset", "c"},
            {"TEXT_LABEL_ASSIGN_INT", "Assign int to text label", "a"},
            {"PUSH_CONST_F6", "Push float constant 6.0", ""},
            {"PUSH_CONST_U8_U8_U8", "Push three unsigned 8-bit constants", "aaa"},
            {"PUSH_CONST_F5", "Push float constant 5.0", ""},
            {"FEQ", "Float equal", ""},
            {"IGE", "Integer greater or equal", ""},
            {"IMUL_S16", "Integer multiply signed 16-bit constant", "c"},
            {"IOFFSET_U8", "Push reference to struct field at offset U8 * 8", "a"},
            {"STRINGHASH", "Hash the string with JOAAT", ""},
            {"GLOBAL_STORE_SR", "Store secure global variable 2", ""},
            {"LOAD_N_S", "Load secure array elements", ""},
            {"FLE", "Float less or equal", ""},
            {"GLOBAL_U24_LOAD", "Load 24-bit global variable", "d"},
            {"PUSH_CONST_F", "Push float constant", "f"},
            {"GLOBAL_U16", "Push reference to 16-bit global variable", "b"},
            {"GLOBAL_LOAD_S", "Load secure global variable", ""},
            {"STATIC_U8", "Push reference to 8-bit static variable", "a"},
            {"ILT_JZ", "Integer greater or equal, jump", "g"},
            {"JZ", "Jump if zero", "g"},
            {"IOFFSET_S16_STORE", "Store value at signed 16-bit offset", "c"},
            {"CALLINDIRECT", "Call script function via pointer", ""},
        }};
    };
}