#pragma once

#define NATIVES_BIN 201

#define SCRDBG_FILEVERSION 1, 0, 0, 0
#define SCRDBG_PRODUCTVERSION SCRDBG_FILEVERSION

#define SCRDBG_FILE_DESCRIPTION "scrDbg"
#define SCRDBG_FILE_VERSION "1.0.0.0"
#define SCRDBG_PRODUCT_NAME SCRDBG_FILE_DESCRIPTION
#define SCRDBG_PRODUCT_VERSION SCRDBG_FILE_VERSION
