#pragma once

#if defined(_M_X64)

namespace rage::rdr3
{
    enum class scrOpcode : uint8_t
    {
        NOP = 19,
        IADD = 67,
        ISUB = 16,
        IMUL = 30,
        IDIV = 89,
        IMOD = 71,
        INOT = 5,
        INEG = 43,
        IEQ = 11,
        INE = 28,
        IGT = 32,
        IGE = 126,
        ILT = 53,
        ILE = 119,
        FADD = 113,
        FSUB = 81,
        FMUL = 36,
        FDIV = 12,
        FMOD = 27,
        FNEG = 101,
        FEQ = 125,
        FNE = 87,
        FGT = 49,
        FGE = 22,
        FLT = 52,
        FLE = 132,
        VADD = 96,
        VSUB = 25,
        VMUL = 7,
        VDIV = 18,
        VNEG = 97,
        IAND = 105,
        IOR = 48,
        IXOR = 73,
        I2F = 54,
        F2I = 69,
        F2V = 56,
        PUSH_CONST_U8 = 109,
        PUSH_CONST_U8_U8 = 111,
        PUSH_CONST_U8_U8_U8 = 123,
        PUSH_CONST_U32 = 55,
        PUSH_CONST_F = 134,
        DUP = 106,
        DROP = 65,
        NATIVE = 3,
        ENTER = 34,
        LEAVE = 80,
        LOAD = 118,
        STORE = 50,
        STORE_REV = 61,
        LOAD_N = 45,
        STORE_N = 6,
        ARRAY_U8 = 99,
        ARRAY_U8_LOAD = 23,
        ARRAY_U8_STORE = 100,
        LOCAL_U8 = 75,
        LOCAL_U8_LOAD = 102,
        LOCAL_U8_STORE = 103,
        STATIC_U8 = 137,
        STATIC_U8_LOAD = 84,
        STATIC_U8_STORE = 78,
        IADD_U8 = 92,
        IMUL_U8 = 20,
        IOFFSET = 86,
        IOFFSET_U8 = 128,
        IOFFSET_U8_LOAD = 39,
        IOFFSET_U8_STORE = 108,
        PUSH_CONST_S16 = 37,
        IADD_S16 = 59,
        IMUL_S16 = 127,
        IOFFSET_S16 = 24,
        IOFFSET_S16_LOAD = 120,
        IOFFSET_S16_STORE = 140,
        ARRAY_U16 = 64,
        ARRAY_U16_LOAD = 2,
        ARRAY_U16_STORE = 10,
        LOCAL_U16 = 88,
        LOCAL_U16_LOAD = 1,
        LOCAL_U16_STORE = 68,
        STATIC_U16 = 70,
        STATIC_U16_LOAD = 58,
        STATIC_U16_STORE = 95,
        GLOBAL_U16 = 135,
        GLOBAL_U16_LOAD = 112,
        GLOBAL_U16_STORE = 74,
        J = 104,
        JZ = 139,
        IEQ_JZ = 21,
        INE_JZ = 114,
        IGT_JZ = 46,
        IGE_JZ = 117,
        ILT_JZ = 138,
        ILE_JZ = 35,
        CALL = 57,
        GLOBAL_U24 = 93,
        GLOBAL_U24_LOAD = 133,
        GLOBAL_U24_STORE = 38,
        PUSH_CONST_U24 = 33,
        SWITCH = 60,
        STRING = 4,
        STRINGHASH = 129,
        TEXT_LABEL_ASSIGN_STRING = 31,
        TEXT_LABEL_ASSIGN_INT = 121,
        TEXT_LABEL_APPEND_STRING = 94,
        TEXT_LABEL_APPEND_INT = 41,
        TEXT_LABEL_COPY = 26,
        CATCH = 110,
        THROW = 85,
        CALLINDIRECT = 141,
        PUSH_CONST_M1 = 8,
        PUSH_CONST_0 = 47,
        PUSH_CONST_1 = 9,
        PUSH_CONST_2 = 17,
        PUSH_CONST_3 = 29,
        PUSH_CONST_4 = 66,
        PUSH_CONST_5 = 98,
        PUSH_CONST_6 = 77,
        PUSH_CONST_7 = 13,
        PUSH_CONST_FM1 = 76,
        PUSH_CONST_F0 = 115,
        PUSH_CONST_F1 = 72,
        PUSH_CONST_F2 = 91,
        PUSH_CONST_F3 = 44,
        PUSH_CONST_F4 = 90,
        PUSH_CONST_F5 = 124,
        PUSH_CONST_F6 = 122,
        PUSH_CONST_F7 = 51,
        LOCAL_LOAD_S = 15,
        LOCAL_STORE_S = 0,
        LOCAL_STORE_SR = 82,
        STATIC_LOAD_S = 14,
        STATIC_STORE_S = 79,
        STATIC_STORE_SR = 116,
        LOAD_N_S = 136,
        GLOBAL_STORE_S = 83,
        GLOBAL_STORE_SR = 130,
        GLOBAL_LOAD_S = 131,
        STORE_N_S = 63,
        STORE_N_SR = 42,
        STATIC_U24 = 62,
        STATIC_U24_LOAD = 107,
        STATIC_U24_STORE = 40
    };

    inline constexpr const char* g_scrOpcodeNames[] = {
        "LOCAL_STORE_S",
        "LOCAL_U16_LOAD",
        "ARRAY_U16_LOAD",
        "NATIVE",
        "STRING",
        "INOT",
        "STORE_N",
        "VMUL",
        "PUSH_CONST_M1",
        "PUSH_CONST_1",
        "ARRAY_U16_STORE",
        "IEQ",
        "FDIV",
        "PUSH_CONST_7",
        "STATIC_LOAD_S",
        "LOCAL_LOAD_S",
        "ISUB",
        "PUSH_CONST_2",
        "VDIV",
        "NOP",
        "IMUL_U8",
        "IEQ_JZ",
        "FGE",
        "ARRAY_U8_LOAD",
        "IOFFSET_S16",
        "VSUB",
        "TEXT_LABEL_COPY",
        "FMOD",
        "INE",
        "PUSH_CONST_3",
        "IMUL",
        "TEXT_LABEL_ASSIGN_STRING",
        "IGT",
        "PUSH_CONST_U24",
        "ENTER",
        "ILE_JZ",
        "FMUL",
        "PUSH_CONST_S16",
        "GLOBAL_U24_STORE",
        "IOFFSET_U8_LOAD",
        "STATIC_U24_STORE",
        "TEXT_LABEL_APPEND_INT",
        "STORE_N_SR",
        "INEG",
        "PUSH_CONST_F3",
        "LOAD_N",
        "IGT_JZ",
        "PUSH_CONST_0",
        "IOR",
        "FGT",
        "STORE",
        "PUSH_CONST_F7",
        "FLT",
        "ILT",
        "I2F",
        "PUSH_CONST_U32",
        "F2V",
        "CALL",
        "STATIC_U16_LOAD",
        "IADD_S16",
        "SWITCH",
        "STORE_REV",
        "STATIC_U24",
        "GLOBAL_STORE_S",
        "ARRAY_U16",
        "DROP",
        "PUSH_CONST_4",
        "IADD",
        "LOCAL_U16_STORE",
        "F2I",
        "STATIC_U16",
        "IMOD",
        "PUSH_CONST_F1",
        "IXOR",
        "GLOBAL_U16_STORE",
        "LOCAL_U8",
        "PUSH_CONST_FM1",
        "PUSH_CONST_6",
        "STATIC_U8_STORE",
        "STATIC_STORE_S",
        "LEAVE",
        "FSUB",
        "LOCAL_STORE_SR",
        "STORE_N_S",
        "STATIC_U8_LOAD",
        "THROW",
        "IOFFSET",
        "FNE",
        "LOCAL_U16",
        "IDIV",
        "PUSH_CONST_F4",
        "PUSH_CONST_F2",
        "IADD_U8",
        "GLOBAL_U24",
        "TEXT_LABEL_APPEND_STRING",
        "STATIC_U16_STORE",
        "VADD",
        "VNEG",
        "PUSH_CONST_5",
        "ARRAY_U8",
        "ARRAY_U8_STORE",
        "FNEG",
        "LOCAL_U8_LOAD",
        "LOCAL_U8_STORE",
        "J",
        "IAND",
        "DUP",
        "STATIC_U24_LOAD",
        "IOFFSET_U8_STORE",
        "PUSH_CONST_U8",
        "CATCH",
        "PUSH_CONST_U8_U8",
        "GLOBAL_U16_LOAD",
        "FADD",
        "INE_JZ",
        "PUSH_CONST_F0",
        "STATIC_STORE_SR",
        "IGE_JZ",
        "LOAD",
        "ILE",
        "IOFFSET_S16_LOAD",
        "TEXT_LABEL_ASSIGN_INT",
        "PUSH_CONST_F6",
        "PUSH_CONST_U8_U8_U8",
        "PUSH_CONST_F5",
        "FEQ",
        "IGE",
        "IMUL_S16",
        "IOFFSET_U8",
        "STRINGHASH",
        "GLOBAL_STORE_SR",
        "GLOBAL_LOAD_S",
        "FLE",
        "GLOBAL_U24_LOAD",
        "PUSH_CONST_F",
        "GLOBAL_U16",
        "LOAD_N_S",
        "STATIC_U8",
        "ILT_JZ",
        "JZ",
        "IOFFSET_S16_STORE",
        "CALLINDIRECT"};
}

#endif