#pragma once

#define X86_INJECTOR_EXE 201
#define NATIVES_GTA4_BIN 202
#define NATIVES_RDR2_BIN 203
#define NATIVES_PAYNE_BIN 204
#define NATIVES_GTA5_BIN 205
#define NATIVES_RDR3_BIN 206

#define SCRDBG_FILEVERSION 3, 0, 0, 0
#define SCRDBG_PRODUCTVERSION SCRDBG_FILEVERSION

#define SCRDBG_FILE_VERSION "3.0.0"
#define SCRDBG_PRODUCT_VERSION SCRDBG_FILE_VERSION

#define SCRDBG_APP_FILE_DESCRIPTION "scrDbgApp"
#define SCRDBG_APP_PRODUCT_NAME SCRDBG_APP_FILE_DESCRIPTION

#define SCRDBG_LIB_FILE_DESCRIPTION "scrDbgLib"
#define SCRDBG_LIB_PRODUCT_NAME SCRDBG_LIB_FILE_DESCRIPTION
