#pragma once

#define NATIVES_BIN 201

#define SCRDBG_FILEVERSION 2, 0, 0, 0
#define SCRDBG_PRODUCTVERSION SCRDBG_FILEVERSION

#define SCRDBG_FILE_VERSION "2.1.0"
#define SCRDBG_PRODUCT_VERSION SCRDBG_FILE_VERSION

#define SCRDBG_APP_FILE_DESCRIPTION "scrDbgApp"
#define SCRDBG_APP_PRODUCT_NAME SCRDBG_APP_FILE_DESCRIPTION

#define SCRDBG_LIB_FILE_DESCRIPTION "scrDbgLib"
#define SCRDBG_LIB_PRODUCT_NAME SCRDBG_LIB_FILE_DESCRIPTION
